import type { Metadata } from 'next'
import { Pacifico } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'

const pacifico = Pacifico({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={pacifico.className}>{children}</body>
    </html>
  )
}
